### ISSUE TITLE
webgl

### ISSUE THREAD

**Issue by trusktr** [BinaryMuse/planetary.js#16]
It'd be awesome to convert this to WebGL so that it's buttery smooth even on older phones if they have a GPU.

I tested on my Lumia 1020 Windows Phone, and the fps was low. I mean, it's Windows, but still. IE11 supports WebGL (most of it), so the globe would probably be smooth on IE11 mobile if it were in WebGL. Many of the Three.js WebGL demos run buttery smooth on my Windows Phone.

Microsoft Edge is about to land on my phone in a day or two, which will have even better WebGL support!

**Comment by BinaryMuse** [comment]
A WebGL version of this project is interesting and would certainly be cool, and it's something I've thought about toying with, but it would be a separate project.
