### ISSUE TITLE
TypeError: Cannot read property 'orthographic' of undefined

### ISSUE THREAD

**Issue by Gabology** [BinaryMuse/planetary.js#20]
Seems that the [npm distribution](https://www.npmjs.com/package/planetary.js) is not working as intended. I tried the basic sample using npm and webpack but I'm getting `TypeError: Cannot read property 'orthographic' of undefined`.

More specifically it seems that `d3.geo` is undefined in this context.

**Comment by peter-bonanni** [comment]
You are using d3v4. To explicitly get d3v3 from package.json I'm using `"d3": "^3"` in mine which fixed this error.

**Comment by christiannaths** [comment]
@Gabology This PR should fix that issue: https://github.com/BinaryMuse/planetary.js/pull/23

**Comment by BinaryMuse** [comment]
This is fixed in `v1.1.3`.
